In [30]:
import torch 

In [31]:
from importlib.metadata import requires


x = torch.arange(4.)
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [32]:
y = 2 * torch.dot(x, x)
y
x.grad

In [33]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [34]:
4*x

tensor([ 0.,  4.,  8., 12.], grad_fn=<MulBackward0>)