In [26]:
import random
import torch
import sys, os
path = "C:\\Users\\longln3\\Dive-Into-DeepLearning\\d2l"
sys.path.append(path)
import d2l as d2l

In [27]:
class SyntheticRegressionData(d2l.DataModule):
    def __init__(self, w, b, noise=0.01, num_train=1000, num_val=1000, batch_size=32):
        super().__init__()
        self.save_hyperparameters()
        n = num_train + num_val
        self.X = torch.randn(n, len(w))
        noise = torch.randn(n, 1) * noise
        self.y = torch.matmul(self.X, w.reshape((-1, 1))) + b + noise

In [28]:
w=torch.tensor([2, -3.4])
b=4.2
data = SyntheticRegressionData(w=w, b=b)
print(data.X.shape)
data.X

torch.Size([2000, 2])


tensor([[ 0.7053,  0.4793],
        [-0.0837, -1.1187],
        [-1.1591, -0.0129],
        ...,
        [-0.0107,  1.0739],
        [-0.7943, -0.7563],
        [-0.2017,  0.5742]])

In [29]:
print(data.y.shape)
data.y

torch.Size([2000, 1])


tensor([[3.9879],
        [7.8180],
        [1.9324],
        ...,
        [0.5432],
        [5.1733],
        [1.8381]])

In [30]:
print(w.shape)
data.X@w.reshape(-1,1) + b

torch.Size([2])


tensor([[3.9811],
        [7.8362],
        [1.9257],
        ...,
        [0.5275],
        [5.1828],
        [1.8443]])

In [ ]:
@d2l.add_to_class(SyntheticRegressionData)
def get_dataloader(self, train):
    