In [1]:
import torch 

In [2]:
from importlib.metadata import requires


x = torch.arange(4.)
x.requires_grad_(True)

tensor([0., 1., 2., 3.], requires_grad=True)

In [3]:
y = 2 * torch.dot(x, x)
y
x.grad

In [4]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [5]:
4*x

tensor([ 0.,  4.,  8., 12.], grad_fn=<MulBackward0>)

In [8]:
# . Note that PyTorch does not automatically reset the gradient buffer when we record a new gradient. 
# Instead the new gradient is added to the already stored gradient. This behavior comes in handy when we want to optimize
# the sum of multiple objective functions. To reset the gradient buffer, we can call x.grad.zero() as follows:
x.grad.zero_()
x.grad

tensor([0., 0., 0., 0.])

In [10]:
x.grad.zero_()
y = x * x
y.backward(gradient=torch.ones(len(y)))
x.grad

tensor([0., 2., 4., 6.])